var keywords = [
"Pathology, Immunology and Laboratory Medicine",
"Internal Medicine",
"Rehabilitation",
"Entomology",
"Pediatrics",
"Medical Education",
"Women's Health",
"Orthopedics",
"Infectious Disease",
"Psychiatry",
"Bioinformatics",
"Gastroenterology",
"Orthopaedics",
"Molecular Genetics",
"Diabetes",
"Statistics",
"Teacher education",
"Cardiovascular Disease",
"Ecology",
"Epidemiology",
"Horticulture",
"Physical Therapy",
"Astronomy",
"Cardiovascular Anesthesiology",
"Hepatology",
"Oncology",
"Special Education",
"Cell Biology",
"Family Medicine",
"Gene Expression",
"Hematology",
"Hypertension",
"Machine Learning",
"Molecular Evolution",
"Molecular biology",
"Speech and Communication Disorders",
"Sports Medicine",
"Water quality",
"Anesthesiology",
"Artificial Intelligence",
"Behavioral Neurology",
"Breast cancer",
"Cancer Biology",
"Clinical Anesthesiology",
"Computational Biology",
"Computer Science",
"Emergency Medicine",
"Evolution",
"Gerontology",
"Head and neck cancers",
"Organic"
];